DELETE FROM `hlstats_Actions` WHERE `game`='tf' and `code` in ('Round_Win','Mini_Round_Win') and `team`='red';

UPDATE `hlstats_Actions` SET `team`='' WHERE `game`='tf' and `code` in ('Round_Win','Mini_Round_Win') and `team`='blue';

INSERT IGNORE INTO `hlstats_Actions` (`game`, `code`, `reward_player`, `reward_team`, `team`, `description`, `for_PlayerActions`, `for_PlayerPlayerActions`, `for_TeamActions`, `for_WorldActions`, `count`, `object`, `event`) VALUES
('tf', 'Round_Win', 0, 10, '', 'Round Win', '', '', '1', '', 0, NULL, NULL),
('tf', 'Mini_Round_Win', 0, 5, '', 'Mini-Round Win', '', '', '1', '', 0, NULL, NULL),
('tf', 'sandvich', 0, 0, '', 'Ate a Sandvich', '1', '', '', '', 0, NULL, NULL),
('zps', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '', '', '', 0, NULL, NULL),
('zps', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '', '', '', 0, NULL, NULL),
('zps', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '', '', '', 0, NULL, NULL),
('zps', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '', '', '', 0, NULL, NULL),
('zps', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '', '', '', 0, NULL, NULL),
('zps', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '', '', '', 0, NULL, NULL),
('zps', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '', '', '', 0, NULL, NULL),
('zps', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '', '', '', 0, NULL, NULL),
('zps', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '', '', '', 0, NULL, NULL),
('zps', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '', '', '', 0, NULL, NULL),
('zps', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '', '', '', 0, NULL, NULL),
('aoc', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '', '', '', 0, NULL, NULL),
('aoc', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '', '', '', 0, NULL, NULL),
('aoc', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '', '', '', 0, NULL, NULL),
('aoc', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '', '', '', 0, NULL, NULL),
('aoc', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '', '', '', 0, NULL, NULL),
('aoc', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '', '', '', 0, NULL, NULL),
('aoc', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '', '', '', 0, NULL, NULL),
('aoc', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '', '', '', 0, NULL, NULL),
('aoc', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '', '', '', 0, NULL, NULL),
('aoc', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '', '', '', 0, NULL, NULL),
('aoc', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '', '', '', 0, NULL, NULL),
('aoc', 'headshot', 2, 0, '', 'Headshot/Decapitate Kill', '1', '', '', '', 0, NULL, NULL);

INSERT IGNORE INTO `hlstats_Awards` (`awardType`, `game`, `code`, `name`, `verb`, `d_winner_id`, `d_winner_count`) VALUES
('O', 'tf', 'sandvich', 'Hungry Hungry Heavy', 'sandviches eaten.', NULL, NULL),
('W', 'zps', 'arms', 'Armed and Dangerous', 'kills with Zombie Arms', NULL, NULL),
('W', 'zps', 'carrierarms', 'Carry on...', 'kills with Carrier Arms', NULL, NULL),
('W', 'zps', 'ak47', 'AK-47', 'kills with AK-47', NULL, NULL),
('W', 'zps', 'mp5', 'MP5', 'kills with MP5', NULL, NULL),
('W', 'zps', 'revolver', 'Revolver', 'kills with Revolver', NULL, NULL),
('W', 'zps', 'glock', 'Glock 17', 'kills with Glock 17', NULL, NULL),
('W', 'zps', 'glock18c', 'Glock 18c', 'kills with Glock 18c', NULL, NULL),
('W', 'zps', 'ppk', 'PPK', 'kills with PPK', NULL, NULL),
('W', 'zps', 'usp', 'H & K USP', 'kills with H & K USP', NULL, NULL),
('W', 'zps', '870', 'Rem. 870', 'kills with Rem. 870', NULL, NULL),
('W', 'zps', 'supershorty', 'Super Shorty', 'kills with Super Shorty', NULL, NULL),
('W', 'zps', 'grenade_frag', 'Grenade', 'kills with Grenades', NULL, NULL),
('W', 'zps', 'sledgehammer', 'Sledgehammer', 'kills with Sledgehammer', NULL, NULL),
('W', 'zps', 'crowbar', 'Hello, I\'m Gordon Freeman', 'kills with Crowbar', NULL, NULL),
('W', 'zps', 'chair', 'Sorry, I thought this was \"pro\" wrestling', 'kills with Chair', NULL, NULL),
('W', 'zps', 'keyboard', 'Keyboard', 'kills with Keyboard', NULL, NULL),
('W', 'zps', 'plank', 'Plank', 'kills with Plank', NULL, NULL),
('W', 'zps', 'shovel', 'Grave Digger', 'kills with Shovel', NULL, NULL),
('W', 'zps', 'golf', 'Fore!', 'kills with Golf Club', NULL, NULL),
('W', 'zps', 'machete', 'Cuttin\' em Down', 'kills with Machete', NULL, NULL),
('W', 'zps', 'fryingpan', 'Frying Pan', 'kills with Frying Pan', NULL, NULL),
('W', 'zps', 'spanner', 'Wrench', 'kills with Wrench', NULL, NULL),
('W', 'zps', 'axe', 'Axe', 'kills with Axe', NULL, NULL),
('W', 'zps', 'tireiron', 'Tire Iron', 'kills with Tire Iron', NULL, NULL),
('W', 'zps', 'hammer', 'Hammer', 'kills with Hammer', NULL, NULL),
('W', 'zps', 'broom', 'Broom', 'kills with Broom', NULL, NULL),
('W', 'zps', 'pot', 'Pot', 'kills with Pot', NULL, NULL),
('W', 'zps', 'racket', 'Tennis Racket', 'kills with Tennis Racket', NULL, NULL),
('W', 'aoc', 'flamberge', 'Flamberge', 'kills with Flamberge', NULL, NULL),
('W', 'aoc', 'longsword', 'Longsword', 'kills with Longsword', NULL, NULL),
('W', 'aoc', 'halberd', 'Knights Halberd', 'kills with Knights Halbred', NULL, NULL),
('W', 'aoc', 'dagger', 'Daggers', 'kills with Dual Daggers', NULL, NULL),
('W', 'aoc', 'flamberge_kiteshield', 'Flamberge & Kite Shield', 'kills with Flamberge & Kite Shield', NULL, NULL),
('W', 'aoc', 'sword2', 'Shortsword', 'kills with Shortsword', NULL, NULL),
('W', 'aoc', 'warhammer', 'Warhammer', 'kills with Warhammer', NULL, NULL),
('W', 'aoc', 'mace', 'Mace', 'kills with Mace', NULL, NULL),
('W', 'aoc', 'mace_buckler', 'Mace & Buckler', 'kills with Mace & Buckler', NULL, NULL),
('W', 'aoc', 'sword01_evil_shield', 'Mason Broadsword & Shield', 'kills with Mason Broadsword & Shield', NULL, NULL),
('W', 'aoc', 'crossbow', 'Crossbow', 'kills with Crossbow', NULL, NULL),
('W', 'aoc', 'longbow', 'Longbow', 'kills with Longbow', NULL, NULL),
('W', 'aoc', 'longsword_kiteshield', 'Longsword & Kite Shield', 'kills with Longsword & Kite Shield', NULL, NULL),
('W', 'aoc', 'sword01_good_shield', 'Knights Broadsword & Shield', 'kills with Knights Broadsword & Shield', NULL, NULL),
('W', 'aoc', 'onehandaxe', 'Hatchet', 'kills with Hatchet', NULL, NULL),
('W', 'aoc', 'doubleaxe', 'Battle Axe', 'kills with Battle Axe', NULL, NULL),
('W', 'aoc', 'flail_evil_shield', 'Mason Flail & Shield', 'kills with Mason Flail & Shield', NULL, NULL),
('W', 'aoc', 'flail_good_shield', 'Knights Flail & Shield', 'kills with Knights Flail & Shield', NULL, NULL),
('W', 'aoc', 'thrown_spear', 'Javelin', 'kills with Javelin', NULL, NULL),
('W', 'aoc', 'shortsword', 'Spiked Mace', 'kills with Spiked Mace', NULL, NULL),
('W', 'aoc', 'spear_buckler', 'Knights Spear & Buckler', 'kills with Knights Spear & Buckler', NULL, NULL),
('W', 'aoc', 'spikedmace_buckler', 'Spiked Mace & Buckler', 'kills with Spiked Mace & Buckler', NULL, NULL),
('W', 'aoc', 'dagger2', 'Dagger', 'kills with Dagger', NULL, NULL),
('W', 'aoc', 'mtest', 'Footman Longsward', 'kills with Footman Longsword', NULL, NULL),
('W', 'aoc', 'thrown_dagger2', 'Thrown Dagger', 'kills with Thrown Dagger', NULL, NULL),
('W', 'aoc', 'spear_buckler2', 'Spiked Mace & Buckler', 'kills with Spiked Mace & Buckler', NULL, NULL),
('W', 'aoc', 'evil_halberd', 'Mason Halberd', 'kills with Mason Halberd', NULL, NULL),
('W', 'aoc', 'env_explosion', 'Fire', 'kills with Fire', NULL, NULL),
('W', 'aoc', 'oilpot', 'Oil Pot', 'kills with Oil Pot', NULL, NULL),
('O', 'aoc', 'headshot', 'Headshot/Decapitation', 'Headshots and Decapitations', NULL, NULL);

INSERT IGNORE INTO `hlstats_Games` (`code`, `name`, `hidden`) VALUES
('zps','Zombie Panic! Source','1'),
('aoc','Age of Chivalry','1');

DELETE FROM `hlstats_PerlConfig` WHERE `parameter` IN ('HLStatsXCountryMaster','MasterBanlistBantime');

DELETE FROM `hlstats_PerlConfig_Default` WHERE `parameter` IN ('HLStatsXCountryMaster','MasterBanlistBantime');

INSERT IGNORE INTO `hlstats_Ranks` (`image`, `minKills`, `maxKills`, `rankName`, `game`) VALUES
('recruit',0,49,'Recruit','zps'),
('private',50,99,'Private','zps'),
('private_firstclass',100,149,'Private First Class','zps'),
('second_lieutenant',150,249,'2nd Lieutenant','zps'),
('first_lieutenant',250,499,'1st Lieutenant','zps'),
('captain',500,749,'Captain','zps'),
('major',750,999,'Major','zps'),
('lieutenant_colonel',1000,1249,'Lieutenant Colonel','zps'),
('colonel',1250,1749,'Colonel','zps'),
('brigadier_general',1750,2499,'Brigardier General','zps'),
('major_general',2500,4999,'Major General','zps'),
('lieutenant_general',5000,7499,'Lieutenant General','zps'),
('general',7500,9999,'General','zps'),
('general_5Star',10000,14999,'5 Star General','zps'),
('ubersoldat',15000,999999999,'The Ubersoldat','zps'),
('recruit',0,49,'Recruit','aoc'),
('private',50,99,'Private','aoc'),
('private_firstclass',100,149,'Private First Class','aoc'),
('second_lieutenant',150,249,'2nd Lieutenant','aoc'),
('first_lieutenant',250,499,'1st Lieutenant','aoc'),
('captain',500,749,'Captain','aoc'),
('major',750,999,'Major','aoc'),
('lieutenant_colonel',1000,1249,'Lieutenant Colonel','aoc'),
('colonel',1250,1749,'Colonel','aoc'),
('brigadier_general',1750,2499,'Brigardier General','aoc'),
('major_general',2500,4999,'Major General','aoc'),
('lieutenant_general',5000,7499,'Lieutenant General','aoc'),
('general',7500,9999,'General','aoc'),
('general_5Star',10000,14999,'5 Star General','aoc'),
('ubersoldat',15000,999999999,'The Ubersoldat','aoc');

INSERT IGNORE INTO `hlstats_Roles` (`game`, `code`, `name`, `hidden`, `picked`, `kills`, `deaths`) VALUES
('ff','Engineer','Engineer','0',0,0,0),
('ff','Spy','Spy','0',0,0,0),
('ff','Soldier','Soldier','0',0,0,0),
('ff','Scout','Scout','0',0,0,0),
('ff','Demoman','Demo Man','0',0,0,0),
('ff','Sniper','Sniper','0',0,0,0),
('ff','Medic','Medic','0',0,0,0),
('ff','Pyro','Pyro','0',0,0,0),
('ff','HWGuy','HWGuy','0',0,0,0),
('ff','Civilian','Civilian','0',0,0,0);

DELETE FROM `hlstats_Servers_Config` WHERE `parameter` IN ('MasterServerData','MasterServerInterval','RawSocketSupport','RawSocketHelpNotice');

DELETE FROM `hlstats_Servers_Config_Default` WHERE `parameter` IN ('MasterServerData','MasterServerInterval','RawSocketSupport','RawSocketHelpNotice');

ALTER TABLE `hlstats_Servers`
ADD COLUMN `lat` varchar(32) NOT NULL default '',
ADD COLUMN `lng` varchar(32) NOT NULL default '',
ADD COLUMN `city` varchar(128) NOT NULL default '',
ADD COLUMN `country` varchar(128) NOT NULL default '';

INSERT IGNORE INTO `hlstats_Teams` (`game`, `code`, `name`, `hidden`, `playerlist_bgcolor`, `playerlist_color`, `playerlist_index`) VALUES
('zps','Undead','Undead', '0', '#F7FF89', '#808700', 1),
('zps','Survivor','Survivors', '0', '#D2E8F7','#0080C0', 2),
('zps','Spectator','Spectator','0', '#D5D5D5','#050505', 0),
('aoc','The Mason Order','The Mason Order','','#FFD5D5','#FF2D2D',2),
('aoc','Agathia Knights','Agathia Knights','','#D2E8F7','#0080C0',1),
('aoc','Spectator','Spectator','0', '#D5D5D5','#050505', 0);

INSERT IGNORE INTO `hlstats_Weapons` (`game`, `code`, `name`, `modifier`, `kills`, `headshots`) VALUES
('zps', 'arms','Zombie',1, 0, 0),
('zps', 'carrierarms','Carrier',1, 0, 0),
('zps', 'ak47','AK-47',1, 0, 0),
('zps', 'mp5','MP5',1, 0, 0),
('zps', 'revolver','Revolver',1, 0, 0),
('zps', 'glock','Glock 17',1, 0, 0),
('zps', 'glock18c','Glock 18c',1, 0, 0),
('zps', 'ppk','Walther PPK',1, 0, 0),
('zps', 'usp','Heckler & Kock USP',1, 0, 0),
('zps', '870','Remington 870',1, 0, 0),
('zps', 'supershorty','Mossberg Super Shorty',1, 0, 0),
('zps', 'grenade_frag','Grenade',1, 0, 0),
('zps', 'sledgehammer','Sledgehammer',1.5, 0, 0),
('zps', 'crowbar','Crowbar',1.5, 0, 0),
('zps', 'chair','Chair',1.5, 0, 0),
('zps', 'keyboard','Keyboard',1.5, 0, 0),
('zps', 'plank','Wooden Plank',1.5, 0, 0),
('zps', 'shovel','Shovel',1.5, 0, 0),
('zps', 'golf','Golf Club',1.5, 0, 0),
('zps', 'machete','Machete',1.5, 0, 0),
('zps', 'fryingpan','Frying Pan',1.5, 0, 0),
('zps', 'spanner','Wrench',1.5, 0, 0),
('zps', 'axe','Axe',1.5, 0, 0),
('zps', 'tireiron','Tire Iron',1.5, 0, 0),
('zps', 'hammer','Hammer',1.5, 0, 0),
('zps', 'broom','Broom',1.5, 0, 0),
('zps', 'pot','Pot',1.5, 0, 0),
('zps', 'world','World',1.5, 0, 0),
('zps', 'physics','Physics',1.5, 0, 0),
('zps', 'racket','Tennis Racket',1.5, 0, 0),
('zps', 'torque','Torque', 1.5, 0, 0),
('aoc', 'flamberge','Flamberge',1, 0, 0),
('aoc', 'longsword','Longsword',1, 0, 0),
('aoc', 'halberd','Knights Halberd',1, 0, 0),
('aoc', 'dagger','Dual Daggers',1, 0, 0),
('aoc', 'flamberge_kiteshield', 'Flamberge & Kite Shield', 1, 0, 0),
('aoc', 'world','World',1, 0, 0),
('aoc', 'chivalry','Chivalry',1, 0, 0),
('aoc', 'sword2','Shortsword',1, 0, 0),
('aoc', 'warhammer','Warhammer',1, 0, 0),
('aoc', 'mace','Mace',1, 0, 0),
('aoc', 'mace_buckler','Mace & Buckler',1, 0, 0),
('aoc', 'sword01_evil_shield', 'Mason Broadsword & Shield', 1, 0, 0),
('aoc', 'crossbow','Crossbow',1, 0, 0),
('aoc', 'longbow','Longbow',1, 0, 0),
('aoc', 'longsword_kiteshield', 'Longsword & Kite Shield', 1, 0, 0),
('aoc', 'sword01_good_shield', 'Knights Broadsword & Shield', 1, 0, 0),
('aoc', 'onehandaxe', 'Hatchet', 1, 0, 0),
('aoc', 'doubleaxe','Battle Axe',1, 0, 0),
('aoc', 'flail_evil_shield','Mason Flail & Shield',1, 0, 0),
('aoc', 'flail_good_shield','Knights Flail & Shield',1, 0, 0),
('aoc', 'thrown_spear', 'Javelin', 1, 0, 0),
('aoc', 'spear_buckler', 'Knights Spear & Buckler', 1, 0, 0),
('aoc', 'dagger2', 'Dagger', 1, 0, 0),
('aoc', 'mtest', 'Footman Longsword', 1, 0, 0),
('aoc', 'thrown_dagger2', 'Thrown Dagger', 1, 0, 0),
('aoc', 'spear_buckler2', 'Mason Spear & Buckler', 1, 0, 0),
('aoc', 'shortsword', 'Spiked Mace', 1, 0, 0),
('aoc', 'spikedmace_buckler','Spiked Mace & Buckler',1, 0, 0),
('aoc', 'evil_halberd', 'Mason Halberd', 1, 0, 0),
('aoc', 'env_explosion', 'Fire', 1, 4, 0),
('aoc', 'oilpot', 'Oil Pot', 1, 1, 0);
