<?php
    if ( !defined('IN_UPDATER') )
    {
        die('Do not access this file directly.');
    }

    $dbversion = 74;
    $version = "1.6.18";

    // Tracker #1552 - Add Counter-Strike: Global Offensive support
    print "Adding CSGO game support. (<a href=\"http://tracker.hlxce.com/issues/1552\">#1552</a>)<br />";
    $db->query("
        INSERT IGNORE INTO `hlstats_Actions` (`game`, `code`, `reward_player`, `reward_team`, `team`, `description`, `for_PlayerActions`, `for_PlayerPlayerActions`, `for_TeamActions`, `for_WorldActions`) VALUES
            ('csgo', 'Begin_Bomb_Defuse_Without_Kit', 0, 0, 'CT', 'Start Defusing the Bomb Without a Defuse Kit', '1', '0', '0', '0'),
            ('csgo', 'Begin_Bomb_Defuse_With_Kit', 0, 0, 'CT', 'Start Defusing the Bomb With a Defuse Kit', '1', '0', '0', '0'),
            ('csgo', 'Planted_The_Bomb', 10, 2, 'TERRORIST', 'Plant the Bomb', '1', '0', '0', '0'),
            ('csgo', 'Defused_The_Bomb', 10, 0, 'CT', 'Defuse the Bomb', '1', '0', '0', '0'),
            ('csgo', 'Touched_A_Hostage', 0, 0, 'CT', 'Touch a Hostage', '1', '0', '0', '0'),
            ('csgo', 'Rescued_A_Hostage', 5, 1, 'CT', 'Rescue a Hostage', '1', '0', '0', '0'),
            ('csgo', 'Killed_A_Hostage', -15, 1, 'CT', 'Kill a Hostage', '1', '0', '0', '0'),
            ('csgo', 'Spawned_With_The_Bomb', 2, 0, 'TERRORIST', 'Spawn with the Bomb', '1', '0', '0', '0'),
            ('csgo', 'Got_The_Bomb', 2, 0, 'TERRORIST', 'Pick up the Bomb', '1', '0', '0', '0'),
            ('csgo', 'Dropped_The_Bomb', -2, 0, 'TERRORIST', 'Drop the Bomb', '1', '0', '0', '0'),
            ('csgo', 'CTs_Win', 0, 2, 'CT', 'All Terrorists eliminated', '0', '0', '1', '0'),
            ('csgo', 'Terrorists_Win', 0, 2, 'TERRORIST', 'All Counter-Terrorists eliminated', '0', '0', '1', '0'),
            ('csgo', 'All_Hostages_Rescued', 0, 10, 'CT', 'Counter-Terrorists rescued all the hostages', '0', '0', '1', '0'),
            ('csgo', 'Target_Bombed', 0, 5, 'TERRORIST', 'Terrorists bombed the target', '0', '0', '1', '0'),
            ('csgo', 'Bomb_Defused', 0, 5, 'CT', 'Counter-Terrorists defused the bomb', '0', '0', '1', '0'),
            ('csgo', 'Escaped_As_VIP', 0, 10, 'CT', 'VIP escaped', '0', '0', '1', '0'),
            ('csgo', 'Assassinated_The_VIP', 0, 6, 'TERRORIST', 'Terrorists assassinated the VIP', '0', '0', '1', '0'),
            ('csgo', 'Became_VIP', 1, 0, 'CT', 'Become the VIP', '1', '0', '0', '0'),
            ('csgo', 'headshot', 1, 0, '', 'Headshot', '1', '0', '0', '0'),
            ('csgo', 'round_mvp', 0, 0, '', 'Round MVP', '1', '0', '0', '0'),
            ('csgo', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
            ('csgo', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
            ('csgo', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
            ('csgo', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
            ('csgo', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
            ('csgo', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
            ('csgo', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
            ('csgo', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
            ('csgo', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
            ('csgo', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
            ('csgo', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0'),
            ('csgo', 'domination', 5, 0, '', 'Domination', '0', '1', '0', '0'),
            ('csgo', 'revenge', 3, 0, '', 'Revenge', '0', '1', '0', '0');
        ");
    
    $db->query("
        INSERT IGNORE INTO `hlstats_Awards` (`awardType`, `game`, `code`, `name`, `verb`) VALUES
            ('W', 'csgo', 'ak47', 'AK47', 'kills with ak47'), 
            ('W', 'csgo', 'AUG', 'Aug', 'kills with aug'), 
            ('W', 'csgo', 'awp', 'AWP', 'kills with awp'),
            ('W', 'csgo', 'deagle', 'Desert Eagle', 'kills with deagle'), 
            ('W', 'csgo', 'elite', 'Dual Berretta Elites', 'kills with elite'),
            ('W', 'csgo', 'famas', 'Fusil Automatique', 'kills with famas'),
            ('W', 'csgo', 'fiveseven', 'Five Seven', 'kills with fiveseven'),
            ('W', 'csgo', 'g3sg1', 'G3 SG1', 'kills with g3sg1'),
            ('W', 'csgo', 'galilar', 'Galil', 'kills with galil'),
            ('W', 'csgo', 'glock', 'Glock', 'kills with glock'),
            ('W', 'csgo', 'hegrenade', 'High Explosive Grenade', 'kills with grenade'),
            ('W', 'csgo', 'firebomb', 'Incendiary Grenade', 'kills with inferno'),
            ('W', 'csgo', 'knife', 'Knife Maniac', 'knifings'),
            ('W', 'csgo', 'm249', 'M249', 'kills with m249'),
            ('W', 'csgo', 'm4a1', 'M4A4', 'kills with m4a4'),
            ('W', 'csgo', 'mac10', 'MAC-10', 'kills with mac10'),
            ('W', 'csgo', 'mag7', 'MAG-7', 'kills with mag7'),
            ('O', 'csgo', 'headshot', 'Headshot King', 'shots in the head'),
            ('W', 'csgo', 'latency', 'Best Latency', 'ms average connection'),
            ('O', 'csgo', 'round_mvp', 'Most Valuable Player', 'times earning Round MVP'),
            ('W', 'csgo', 'mostkills', 'Most Kills', 'kills'),
            ('W', 'csgo', 'suicide', 'Suicides', 'suicides'),
            ('W', 'csgo', 'teamkills', 'Team Killer', 'team kills'),
            ('W', 'csgo', 'mp7', 'MP7', 'kills with mp7'),
            ('W', 'csgo', 'mp9', 'MP9', 'kills with mp9'),
            ('W', 'csgo', 'negev', 'Negev', 'kills with negev'),
            ('W', 'csgo', 'nova', 'Nova', 'kills with nova'),
            ('W', 'csgo', 'hkp2000', 'P2000', 'kills with p2000'),
            ('W', 'csgo', 'p250', 'P250', 'kills with p250'),
            ('W', 'csgo', 'p90', 'P90', 'kills with p90'),
            ('W', 'csgo', 'bizon', 'PP-Bizon', 'kills with pp-bizon'),
            ('W', 'csgo', 'sawedoff', 'Sawed-Off', 'kills with sawed-off'),
            ('W', 'csgo', 'scar20', 'SCAR-20', 'kills with scar-20'),
            ('W', 'csgo', 'sg553', 'SG 553', 'kills with sg553'),
            ('W', 'csgo', 'ssg08', 'SSG 08', 'kills with ssg08'),
            ('W', 'csgo', 'tec9', 'Tec-9', 'kills with Tec-9'),
            ('O', 'csgo', 'Defused_The_Bomb', 'Top Defuser', 'bomb defusions'),
            ('O', 'csgo', 'Planted_The_Bomb', 'Top Demolitionist', 'bomb plantings'),
            ('O', 'csgo', 'Killed_A_Hostage', 'Top Hostage Killer', 'hostages killed'),
            ('O', 'csgo', 'Rescued_A_Hostage', 'Top Hostage Rescuer', 'hostages rescued'),
            ('W', 'csgo', 'ump45', 'UMP-45', 'kills with ump45'),
            ('W', 'csgo', 'xm1014', 'XM automatic Shotgun', 'kills with xm1014'),
            ('W', 'csgo', 'taser', 'Zeus x27', 'kills with taser');
    ");
    
    $db->query("
        INSERT IGNORE INTO `hlstats_Games` (`code`, `name`, `realgame`, `hidden`) VALUES 
            ('csgo','Counter-Strike: Global Offensive','csgo','1');
    ");
    
    $db->query("
        INSERT IGNORE INTO `hlstats_Games_Defaults` (`code`, `parameter`, `value`) VALUES
            ('csgo', 'Admins', ''),
            ('csgo', 'AutoBanRetry', '0'),
            ('csgo', 'AutoTeamBalance', '0'),
            ('csgo', 'BonusRoundIgnore', '0'),
            ('csgo', 'BonusRoundTime', '0'),
            ('csgo', 'BroadCastEvents', '1'),
            ('csgo', 'BroadCastPlayerActions', '1'),
            ('csgo', 'ConnectAnnounce', '1'),
            ('csgo', 'DefaultDisplayEvents', '1'),
            ('csgo', 'DisplayResultsInBrowser', '0'),
            ('csgo', 'EnablePublicCommands', '1'),
            ('csgo', 'GameEngine', '3'),
            ('csgo', 'GameType', '0'),
            ('csgo', 'HLStatsURL', 'http://yoursite.com/hlstats'),
            ('csgo', 'IgnoreBots', '1'),
            ('csgo', 'MinimumPlayersRank', '0'),
            ('csgo', 'MinPlayers', '4'),
            ('csgo', 'PlayerEvents', '1'),
            ('csgo', 'ShowStats', '1'),
            ('csgo', 'SkillMode', '0'),
            ('csgo', 'SuicidePenalty', '5'),
            ('csgo', 'SwitchAdmins', '0'),
            ('csgo', 'TKPenalty', '25'),
            ('csgo', 'TrackServerLoad', '1'),
            ('csgo', 'UpdateHostname', '1');
    ");

    $db->query("
        INSERT IGNORE INTO `hlstats_Games_Supported` (`code`, `name`) VALUES
            ('csgo', 'Counter-Strike: Global Offensive');
    ");
    
    $db->query("
        INSERT INTO `hlstats_Heatmap_Config` (`map`, `game`, `xoffset`, `yoffset`, `flipx`, `flipy`, `days`, `brush`, `scale`, `font`, `thumbw`, `thumbh`, `cropx1`, `cropy1`, `cropx2`, `cropy2`) VALUES
            ('de_dust2', 'csgo', 3102, 3164, 0, 1, 30, 'small', 4.2, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_dust', 'csgo', 3798, 3947, 0, 1, 30, 'small', 6, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_train', 'csgo', 2212, 2193, 0, 1, 30, 'small', 4, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('cs_italy', 'csgo', 3156, 2632, 0, 1, 30, 'small', 4.5, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_aztec', 'csgo', 3226, 2861, 0, 1, 30, 'small', 4.7, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_nuke', 'csgo', 2803, 1309, 0, 1, 30, 'small', 5, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_inferno', 'csgo', 2577, 4184, 0, 1, 30, 'small', 5, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('cs_office', 'csgo', 1931, 1183, 0, 1, 30, 'small', 3, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_dust2_se', 'csgo', 3121, 3551, 0, 1, 30, 'small', 4.5, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_dust_se', 'csgo', 3359, 3773, 0, 1, 30, 'small', 5.5, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_train_se', 'csgo', 2074, 1950, 0, 1, 30, 'small', 3.9, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('cs_italy_se', 'csgo', 2585, 2648, 0, 1, 30, 'small', 4.5, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_aztec_se', 'csgo', 3226, 2861, 0, 1, 30, 'small', 4.7, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_nuke_se', 'csgo', 3023, 1493, 0, 1, 30, 'small', 5.3, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_inferno_se', 'csgo', 3173, 2682, 0, 1, 30, 'small', 4.8, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('cs_office_se', 'csgo', 1930, 1389, 0, 1, 30, 'small', 3.6, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('ar_baggage', 'csgo', 1913, 1701, 0, 1, 30, 'small', 3, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('ar_shoots', 'csgo', 1511, 1801, 0, 1, 30, 'small', 2.5, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_lake', 'csgo', 1478, 1115, 0, 1, 30, 'small', 3.7, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_bank', 'csgo', 2064, 1148, 0, 1, 30, 'small', 3.4, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_safehouse', 'csgo', 348, 2360, 0, 1, 30, 'small', 3.8, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_shorttrain', 'csgo', 2226, 2618, 0, 1, 30, 'small', 4.1, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_stmarc', 'csgo', 9206, 8383, 0, 1, 30, 'small', 3, 10, 0.170312, 0.170312, 0, 0, 0, 0),
            ('de_sugarcane', 'csgo', 4204, 1359, 0, 1, 30, 'small', 4.3, 10, 0.170312, 0.170312, 0, 0, 0, 0);
    ");
    
    $db->query("
        INSERT IGNORE INTO `hlstats_Ranks` (`game`, `image`, `minKills`, `maxKills`, `rankName`) VALUES
            ('csgo', 'recruit', '0', '49', 'Recruit'),
            ('csgo', 'private', '50', '99', 'Private'),
            ('csgo', 'private-first-class', '100', '199', 'Private First Class'),
            ('csgo', 'lance-corporal', '200', '299', 'Lance Corporal'),
            ('csgo', 'corporal', '300', '399', 'Corporal'),
            ('csgo', 'sergeant', '400', '499', 'Sergeant'),
            ('csgo', 'staff-sergeant', '500', '599', 'Staff Sergeant'),
            ('csgo', 'gunnery-sergeant', '600', '699', 'Gunnery Sergeant'),
            ('csgo', 'master-sergeant', '700', '799', 'Master Sergeant'),
            ('csgo', 'first-sergeant', '800', '899', 'First Sergeant'),
            ('csgo', 'master-chief', '900', '999', 'Master Chief'),
            ('csgo', 'sergeant-major', '1000', '1199', 'Sergeant Major'),
            ('csgo', 'ensign', '1200', '1399', 'Ensign'),
            ('csgo', 'third-lieutenant', '1400', '1599', 'Third Lieutenant'),
            ('csgo', 'second-lieutenant', '1600', '1799', 'Second Lieutenant'),
            ('csgo', 'first-lieutenant', '1800', '1999', 'First Lieutenant'),
            ('csgo', 'captain', '2000', '2249', 'Captain'),
            ('csgo', 'group-captain', '2250', '2499', 'Group Captain'),
            ('csgo', 'senior-captain', '2500', '2749', 'Senior Captain'),
            ('csgo', 'lieutenant-major', '2750', '2999', 'Lieutenant Major'),
            ('csgo', 'major', '3000', '3499', 'Major'),
            ('csgo', 'group-major', '3500', '3999', 'Group Major'),
            ('csgo', 'lieutenant-commander', '4000', '4499', 'Lieutenant Commander'),
            ('csgo', 'commander', '4500', '4999', 'Commander'),
            ('csgo', 'group-commander', '5000', '5749', 'Group Commander'),
            ('csgo', 'lieutenant-colonel', '5750', '6499', 'Lieutenant Colonel'),
            ('csgo', 'colonel', '6500', '7249', 'Colonel'),
            ('csgo', 'brigadier', '7250', '7999', 'Brigadier'),
            ('csgo', 'brigadier-general', '8000', '8999', 'Brigadier General'),
            ('csgo', 'major-general', '9000', '9999', 'Major General'),
            ('csgo', 'lieutenant-general', '10000', '12499', 'Lieutenant General'),
            ('csgo', 'general', '12500', '14999', 'General'),
            ('csgo', 'commander-general', '15000', '17499', 'Commander General'),
            ('csgo', 'field-vice-marshal', '17500', '19999', 'Field Vice Marshal'),
            ('csgo', 'field-marshal', '20000', '22499', 'Field Marshal'),
            ('csgo', 'vice-commander-of-the-army', '22500', '24999', 'Vice Commander of the Army'),
            ('csgo', 'commander-of-the-army', '25000', '27499', 'Commander of the Army'),
            ('csgo', 'high-commander', '27500', '29999', 'High Commander'),
            ('csgo', 'supreme-commander', '30000', '34999', 'Supreme Commander'),
            ('csgo', 'terminator', '35000', '9999999', 'Terminator');
    ");
    
  $db->query("
        INSERT IGNORE INTO `hlstats_Ribbons` (`awardCode`, `awardCount`, `special`, `game`, `image`, `ribbonName`) VALUES
            ('ak47', 1, 0, 'csgo', '1_ak47.png', 'Award of AK47'),
            ('awp', 1, 0, 'csgo', '1_awp.png', 'Award of AWP Sniper'),
            ('bizon', 1, 0, 'csgo', '1_bizon.png', 'Award of PP Bizon'),
            ('deagle', 1, 0, 'csgo', '1_deagle.png', 'Award of Desert Eagle'),
            ('elite', 1, 0, 'csgo', '1_elite.png', 'Award of Dual Beretta Elites'),
            ('firebomb', 1, 0, 'csgo', '1_firebomb.png', 'Award of Inferno'),
            ('fiveseven', 1, 0, 'csgo', '1_fiveseven.png', 'Award of Five-Seven'),
            ('g3sg1', 1, 0, 'csgo', '1_g3sg1.png', 'Award of G3 SG1'),
            ('galilar', 1, 0, 'csgo', '1_galilar.png', 'Award of Galilar'),
            ('glock', 1, 0, 'csgo', '1_glock.png', 'Award of Glock'),
            ('hegrenade', 1, 0, 'csgo', '1_hegrenade.png', 'Award of HE Grenades'),
            ('P2000', 1, 0, 'csgo', '1_hkp2000.png', 'Award of P2000'),
            ('knife', 1, 0, 'csgo', '1_knife.png', 'Award of Combat Knife'),
            ('m4a1', 1, 0, 'csgo', '1_m4a1.png', 'Award of M4A4'),
            ('m249', 1, 0, 'csgo', '1_m249.png', 'Award of M249'),
            ('mac10', 1, 0, 'csgo', '1_mac10.png', 'Award of MAC-10'),
            ('mag7', 1, 0, 'csgo', '1_mag7.png', 'Award of MAG-7'),
            ('mp7', 1, 0, 'csgo', '1_mp7.png', 'Award of MP7'),
            ('mp9', 1, 0, 'csgo', '1_mp9.png', 'Award of MP9'),
            ('negev', 1, 0, 'csgo', '1_negev.png', 'Award of Negev'),
            ('nova', 1, 0, 'csgo', '1_nova.png', 'Award of Nova'),
            ('p90', 1, 0, 'csgo', '1_p90.png', 'Award of P90'),
            ('p250', 1, 0, 'csgo', '1_p250.png', 'Award of P250'),
            ('sawedoff', 1, 0, 'csgo', '1_sawedoff.png', 'Award of Sawed-Off'),
            ('scar20', 1, 0, 'csgo', '1_scar20.png', 'Award of SCAR-20'),
            ('sg553', 1, 0, 'csgo', '1_sg553.png', 'Award of SG 553'),
            ('sg08', 1, 0, 'csgo', '1_sg08.png', 'Award of SG 08'),
            ('taser', 1, 0, 'csgo', '1_taser.png', 'Award of Zeus x27'),
            ('tec9', 1, 0, 'csgo', '1_tec9.png', 'Award of Tec9'),
            ('ump45', 1, 0, 'csgo', '1_ump45.png', 'Award of UMP-45'),
            ('xm1014', 1, 0, 'csgo', '1_xm1014.png', 'Award of XM Shotgun'),
            ('ak47', 5, 0, 'csgo', '2_ak47.png', 'Bronze AK47'),
            ('awp', 5, 0, 'csgo', '2_awp.png', 'Bronze AWP Sniper'),
            ('bizon', 5, 0, 'csgo', '2_bizon.png', 'Bronze PP Bizon'),
            ('deagle', 5, 0, 'csgo', '2_deagle.png', 'Bronze Desert Eagle'),
            ('elite', 5, 0, 'csgo', '2_elite.png', 'Bronze Dual Beretta Elites'),
            ('firebomb', 5, 0, 'csgo', '2_firebomb.png', 'Bronze Inferno'),
            ('fiveseven', 5, 0, 'csgo', '2_fiveseven.png', 'Bronze Five-Seven'),
            ('g3sg1', 5, 0, 'csgo', '2_g3sg1.png', 'Bronze G3 SG1'),
            ('galilar', 5, 0, 'csgo', '2_galilar.png', 'Bronze Galilar'),
            ('glock', 5, 0, 'csgo', '2_glock.png', 'Bronze Glock'),
            ('hegrenade', 5, 0, 'csgo', '2_hegrenade.png', 'Bronze HE Grenades'),
            ('P2000', 5, 0, 'csgo', '2_hkp2000.png', 'Bronze P2000'),
            ('knife', 5, 0, 'csgo', '2_knife.png', 'Bronze Combat Knife'),
            ('m4a1', 5, 0, 'csgo', '2_m4a1.png', 'Bronze M4A4'),
            ('m249', 5, 0, 'csgo', '2_m249.png', 'Bronze M249'),
            ('mac10', 5, 0, 'csgo', '2_mac10.png', 'Bronze MAC-10'),
            ('mag7', 5, 0, 'csgo', '2_mag7.png', 'Bronze MAG-7'),
            ('mp7', 5, 0, 'csgo', '2_mp7.png', 'Bronze MP7'),
            ('mp9', 5, 0, 'csgo', '2_mp9.png', 'Bronze MP9'),
            ('negev', 5, 0, 'csgo', '2_negev.png', 'Bronze Negev'),
            ('nova', 5, 0, 'csgo', '2_nova.png', 'Bronze Nova'),
            ('p90', 5, 0, 'csgo', '2_p90.png', 'Bronze P90'),
            ('p250', 5, 0, 'csgo', '2_p250.png', 'Bronze P250'),
            ('sawedoff', 5, 0, 'csgo', '2_sawedoff.png', 'Bronze Sawed-Off'),
            ('scar20', 5, 0, 'csgo', '2_scar20.png', 'Bronze SCAR-20'),
            ('sg553', 5, 0, 'csgo', '2_sg553.png', 'Bronze SG 553'),
            ('sg08', 5, 0, 'csgo', '2_sg08.png', 'Bronze SG 08'),
            ('taser', 5, 0, 'csgo', '2_taser.png', 'Bronze Zeus x27'),
            ('tec9', 5, 0, 'csgo', '2_tec9.png', 'Bronze Tec9'),
            ('ump45', 5, 0, 'csgo', '2_ump45.png', 'Bronze UMP-45'),
            ('xm1014', 5, 0, 'csgo', '2_xm1014.png', 'Bronze XM Shotgun'),
            ('ak47', 12, 0, 'csgo', '3_ak47.png', 'Silver AK47'),
            ('awp', 12, 0, 'csgo', '3_awp.png', 'Silver AWP Sniper'),
            ('bizon', 12, 0, 'csgo', '3_bizon.png', 'Silver PP Bizon'),
            ('deagle', 12, 0, 'csgo', '3_deagle.png', 'Silver Desert Eagle'),
            ('elite', 12, 0, 'csgo', '3_elite.png', 'Silver Dual Beretta Elites'),
            ('firebomb', 12, 0, 'csgo', '3_firebomb.png', 'Silver Inferno'),
            ('fiveseven', 12, 0, 'csgo', '3_fiveseven.png', 'Silver Five-Seven'),
            ('g3sg1', 12, 0, 'csgo', '3_g3sg1.png', 'Silver G3 SG1'),
            ('galilar', 12, 0, 'csgo', '3_galilar.png', 'Silver Galilar'),
            ('glock', 12, 0, 'csgo', '3_glock.png', 'Silver Glock'),
            ('hegrenade', 12, 0, 'csgo', '3_hegrenade.png', 'Silver HE Grenades'),
            ('P2000', 12, 0, 'csgo', '3_hkp2000.png', 'Silver P2000'),
            ('knife', 12, 0, 'csgo', '3_knife.png', 'Silver Combat Knife'),
            ('m4a1', 12, 0, 'csgo', '3_m4a1.png', 'Silver M4A4'),
            ('m249', 12, 0, 'csgo', '3_m249.png', 'Silver M249'),
            ('mac10', 12, 0, 'csgo', '3_mac10.png', 'Silver MAC-10'),
            ('mag7', 12, 0, 'csgo', '3_mag7.png', 'Silver MAG-7'),
            ('mp7', 12, 0, 'csgo', '3_mp7.png', 'Silver MP7'),
            ('mp9', 12, 0, 'csgo', '3_mp9.png', 'Silver MP9'),
            ('negev', 12, 0, 'csgo', '3_negev.png', 'Silver Negev'),
            ('nova', 12, 0, 'csgo', '3_nova.png', 'Silver Nova'),
            ('p90', 12, 0, 'csgo', '3_p90.png', 'Silver P90'),
            ('p250', 12, 0, 'csgo', '3_p250.png', 'Silver P250'),
            ('sawedoff', 12, 0, 'csgo', '3_sawedoff.png', 'Silver Sawed-Off'),
            ('scar20', 12, 0, 'csgo', '3_scar20.png', 'Silver SCAR-20'),
            ('sg553', 12, 0, 'csgo', '3_sg553.png', 'Silver SG 553'),
            ('sg08', 12, 0, 'csgo', '3_sg08.png', 'Silver SG 08'),
            ('taser', 12, 0, 'csgo', '3_taser.png', 'Silver Zeus x27'),
            ('tec9', 12, 0, 'csgo', '3_tec9.png', 'Silver Tec9'),
            ('ump45', 12, 0, 'csgo', '3_ump45.png', 'Silver UMP-45'),
            ('xm1014', 12, 0, 'csgo', '3_xm1014.png', 'Silver XM Shotgun'),
            ('ak47', 20, 0, 'csgo', '4_ak47.png', 'Gold AK47'),
            ('awp', 20, 0, 'csgo', '4_awp.png', 'Gold AWP Sniper'),
            ('bizon', 20, 0, 'csgo', '4_bizon.png', 'Gold PP Bizon'),
            ('deagle', 20, 0, 'csgo', '4_deagle.png', 'Gold Desert Eagle'),
            ('elite', 20, 0, 'csgo', '4_elite.png', 'Gold Dual Beretta Elites'),
            ('firebomb', 20, 0, 'csgo', '4_firebomb.png', 'Gold Inferno'),
            ('fiveseven', 20, 0, 'csgo', '4_fiveseven.png', 'Gold Five-Seven'),
            ('g3sg1', 20, 0, 'csgo', '4_g3sg1.png', 'Gold G3 SG1'),
            ('galilar', 20, 0, 'csgo', '4_galilar.png', 'Gold Galilar'),
            ('glock', 20, 0, 'csgo', '4_glock.png', 'Gold Glock'),
            ('hegrenade', 20, 0, 'csgo', '4_hegrenade.png', 'Gold HE Grenades'),
            ('P2000', 20, 0, 'csgo', '4_hkp2000.png', 'Gold P2000'),
            ('knife', 20, 0, 'csgo', '4_knife.png', 'Gold Combat Knife'),
            ('m4a1', 20, 0, 'csgo', '4_m4a1.png', 'Gold M4A4'),
            ('m249', 20, 0, 'csgo', '4_m249.png', 'Gold M249'),
            ('mac10', 20, 0, 'csgo', '4_mac10.png', 'Gold MAC-10'),
            ('mag7', 20, 0, 'csgo', '4_mag7.png', 'Gold MAG-7'),
            ('mp7', 20, 0, 'csgo', '4_mp7.png', 'Gold MP7'),
            ('mp9', 20, 0, 'csgo', '4_mp9.png', 'Gold MP9'),
            ('negev', 20, 0, 'csgo', '4_negev.png', 'Gold Negev'),
            ('nova', 20, 0, 'csgo', '4_nova.png', 'Gold Nova'),
            ('p90', 20, 0, 'csgo', '4_p90.png', 'Gold P90'),
            ('p250', 20, 0, 'csgo', '4_p250.png', 'Gold P250'),
            ('sawedoff', 20, 0, 'csgo', '4_sawedoff.png', 'Gold Sawed-Off'),
            ('scar20', 20, 0, 'csgo', '4_scar20.png', 'Gold SCAR-20'),
            ('sg553', 20, 0, 'csgo', '4_sg553.png', 'Gold SG 553'),
            ('sg08', 20, 0, 'csgo', '4_sg08.png', 'Gold SG 08'),
            ('taser', 20, 0, 'csgo', '4_taser.png', 'Gold Zeus x27'),
            ('tec9', 20, 0, 'csgo', '4_tec9.png', 'Gold Tec9'),
            ('ump45', 20, 0, 'csgo', '4_ump45.png', 'Gold UMP-45'),
            ('xm1014', 20, 0, 'csgo', '4_xm1014.png', 'Gold XM Shotgun'),
            ('ak47', 30, 0, 'csgo', '5_ak47.png', 'Platinum AK47'),
            ('awp', 30, 0, 'csgo', '5_awp.png', 'Platinum AWP Sniper'),
            ('bizon', 30, 0, 'csgo', '5_bizon.png', 'Platinum PP Bizon'),
            ('deagle', 30, 0, 'csgo', '5_deagle.png', 'Platinum Desert Eagle'),
            ('elite', 30, 0, 'csgo', '5_elite.png', 'Platinum Dual Beretta Elites'),
            ('firebomb', 30, 0, 'csgo', '5_firebomb.png', 'Platinum Inferno'),
            ('fiveseven', 30, 0, 'csgo', '5_fiveseven.png', 'Platinum Five-Seven'),
            ('g3sg1', 30, 0, 'csgo', '5_g3sg1.png', 'Platinum G3 SG1'),
            ('galilar', 30, 0, 'csgo', '5_galilar.png', 'Platinum Galilar'),
            ('glock', 30, 0, 'csgo', '5_glock.png', 'Platinum Glock'),
            ('hegrenade', 30, 0, 'csgo', '5_hegrenade.png', 'Platinum HE Grenades'),
            ('P2000', 30, 0, 'csgo', '5_hkp2000.png', 'Platinum P2000'),
            ('knife', 30, 0, 'csgo', '5_knife.png', 'Platinum Combat Knife'),
            ('m4a1', 30, 0, 'csgo', '5_m4a1.png', 'Platinum M4A4'),
            ('m249', 30, 0, 'csgo', '5_m249.png', 'Platinum M249'),
            ('mac10', 30, 0, 'csgo', '5_mac10.png', 'Platinum MAC-10'),
            ('mag7', 30, 0, 'csgo', '5_mag7.png', 'Platinum MAG-7'),
            ('mp7', 30, 0, 'csgo', '5_mp7.png', 'Platinum MP7'),
            ('mp9', 30, 0, 'csgo', '5_mp9.png', 'Platinum MP9'),
            ('negev', 30, 0, 'csgo', '5_negev.png', 'Platinum Negev'),
            ('nova', 30, 0, 'csgo', '5_nova.png', 'Platinum Nova'),
            ('p90', 30, 0, 'csgo', '5_p90.png', 'Platinum P90'),
            ('p250', 30, 0, 'csgo', '5_p250.png', 'Platinum P250'),
            ('sawedoff', 30, 0, 'csgo', '5_sawedoff.png', 'Platinum Sawed-Off'),
            ('scar20', 30, 0, 'csgo', '5_scar20.png', 'Platinum SCAR-20'),
            ('sg553', 30, 0, 'csgo', '5_sg553.png', 'Platinum SG 553'),
            ('sg08', 30, 0, 'csgo', '5_sg08.png', 'Platinum SG 08'),
            ('taser', 30, 0, 'csgo', '5_taser.png', 'Platinum Zeus x27'),
            ('tec9', 30, 0, 'csgo', '5_tec9.png', 'Platinum Tec9'),
            ('ump45', 30, 0, 'csgo', '5_ump45.png', 'Platinum UMP-45'),
            ('xm1014', 30, 0, 'csgo', '5_xm1014.png', 'Platinum XM Shotgun'),
            ('ak47', 50, 0, 'csgo', '6_ak47.png', 'Supreme AK47'),
            ('awp', 50, 0, 'csgo', '6_awp.png', 'Supreme AWP Sniper'),
            ('bizon', 50, 0, 'csgo', '6_bizon.png', 'Supreme PP Bizon'),
            ('deagle', 50, 0, 'csgo', '6_deagle.png', 'Supreme Desert Eagle'),
            ('elite', 50, 0, 'csgo', '6_elite.png', 'Supreme Dual Beretta Elites'),
            ('firebomb', 50, 0, 'csgo', '6_firebomb.png', 'Supreme Inferno'),
            ('fiveseven', 50, 0, 'csgo', '6_fiveseven.png', 'Supreme Five-Seven'),
            ('g3sg1', 50, 0, 'csgo', '6_g3sg1.png', 'Supreme G3 SG1'),
            ('galilar', 50, 0, 'csgo', '6_galilar.png', 'Supreme Galilar'),
            ('glock', 50, 0, 'csgo', '6_glock.png', 'Supreme Glock'),
            ('hegrenade', 50, 0, 'csgo', '6_hegrenade.png', 'Supreme HE Grenades'),
            ('P2000', 50, 0, 'csgo', '6_hkp2000.png', 'Supreme P2000'),
            ('knife', 50, 0, 'csgo', '6_knife.png', 'Supreme Combat Knife'),
            ('m4a1', 50, 0, 'csgo', '6_m4a1.png', 'Supreme M4A4'),
            ('m249', 50, 0, 'csgo', '6_m249.png', 'Supreme M249'),
            ('mac10', 50, 0, 'csgo', '6_mac10.png', 'Supreme MAC-10'),
            ('mag7', 50, 0, 'csgo', '6_mag7.png', 'Supreme MAG-7'),
            ('mp7', 50, 0, 'csgo', '6_mp7.png', 'Supreme MP7'),
            ('mp9', 50, 0, 'csgo', '6_mp9.png', 'Supreme MP9'),
            ('negev', 50, 0, 'csgo', '6_negev.png', 'Supreme Negev'),
            ('nova', 50, 0, 'csgo', '6_nova.png', 'Supreme Nova'),
            ('p90', 50, 0, 'csgo', '6_p90.png', 'Supreme P90'),
            ('p250', 50, 0, 'csgo', '6_p250.png', 'Supreme P250'),
            ('sawedoff', 50, 0, 'csgo', '6_sawedoff.png', 'Supreme Sawed-Off'),
            ('scar20', 50, 0, 'csgo', '6_scar20.png', 'Supreme SCAR-20'),
            ('sg553', 50, 0, 'csgo', '6_sg553.png', 'Supreme SG 553'),
            ('sg08', 50, 0, 'csgo', '6_sg08.png', 'Supreme SG 08'),
            ('taser', 50, 0, 'csgo', '6_taser.png', 'Supreme Zeus x27'),
            ('tec9', 50, 0, 'csgo', '6_tec9.png', 'Supreme Tec9'),
            ('ump45', 50, 0, 'csgo', '6_ump45.png', 'Supreme UMP-45'),
            ('xm1014', 50, 0, 'csgo', '6_xm1014.png', 'Supreme XM Shotgun'),
            ('Defused_The_Bomb', 1, 0, 'csgo', '1_defused_the_bomb.png', 'Award of Bomb Defuser'),
            ('Planted_The_Bomb', 1, 0, 'csgo', '1_planted_the_bomb.png', 'Award of Bomb Planter'),
            ('Rescued_A_Hostage', 1, 0, 'csgo', '1_rescued_a_hostage.png', 'Award of Hostage Rescuer'),
            ('Killed_A_Hostage', 1, 0, 'csgo', '1_killed_a_hostage.png', 'Award of Hostage Killer'),
            ('latency', 1, 0, 'csgo', '1_latency.png', 'Award of Lowpinger'),
            ('headshot', 1, 0, 'csgo', '1_headshot.png', 'Award of Headshots'),
            ('Defused_The_Bomb', 5, 0, 'csgo', '2_defused_the_bomb.png', 'Bronze Bomb Defuser'),
            ('Planted_The_Bomb', 5, 0, 'csgo', '2_planted_the_bomb.png', 'Bronze Bomb Planter'),
            ('Rescued_A_Hostage', 5, 0, 'csgo', '2_rescued_a_hostage.png', 'Bronze Hostage Rescuer'),
            ('Killed_A_Hostage', 5, 0, 'csgo', '2_killed_a_hostage.png', 'Bronze Hostage Killer'),
            ('latency', 5, 0, 'csgo', '2_latency.png', 'Bronze Lowpinger'),
            ('headshot', 5, 0, 'csgo', '2_headshot.png', 'Bronze Headshots'),
            ('Defused_The_Bomb', 12, 0, 'csgo', '3_defused_the_bomb.png', 'Silver Bomb Defuser'),
            ('Planted_The_Bomb', 12, 0, 'csgo', '3_planted_the_bomb.png', 'Silver Bomb Planter'),
            ('Rescued_A_Hostage', 12, 0, 'csgo', '3_rescued_a_hostage.png', 'Silver Hostage Rescuer'),
            ('Killed_A_Hostage', 12, 0, 'csgo', '3_killed_a_hostage.png', 'Silver Hostage Killer'),
            ('latency', 12, 0, 'csgo', '3_latency.png', 'Silver Lowpinger'),
            ('headshot', 12, 0, 'csgo', '3_headshot.png', 'Silver Headshots'),
            ('Defused_The_Bomb', 20, 0, 'csgo', '4_defused_the_bomb.png', 'Gold Bomb Defuser'),
            ('Planted_The_Bomb', 20, 0, 'csgo', '4_planted_the_bomb.png', 'Gold Bomb Planter'),
            ('Rescued_A_Hostage', 20, 0, 'csgo', '4_rescued_a_hostage.png', 'Gold Hostage Rescuer'),
            ('Killed_A_Hostage', 20, 0, 'csgo', '4_killed_a_hostage.png', 'Gold Hostage Killer'),
            ('latency', 20, 0, 'csgo', '4_latency.png', 'Gold Lowpinger'),
            ('headshot', 20, 0, 'csgo', '4_headshot.png', 'Gold Headshots'),
            ('Defused_The_Bomb', 30, 0, 'csgo', '5_defused_the_bomb.png', 'Platinum Bomb Defuser'),
            ('Planted_The_Bomb', 30, 0, 'csgo', '5_planted_the_bomb.png', 'Platinum Bomb Planter'),
            ('Rescued_A_Hostage', 30, 0, 'csgo', '5_rescued_a_hostage.png', 'Platinum Hostage Rescuer'),
            ('Killed_A_Hostage', 30, 0, 'csgo', '5_killed_a_hostage.png', 'Platinum Hostage Killer'),
            ('latency', 30, 0, 'csgo', '5_latency.png', 'Platinum Lowpinger'),
            ('headshot', 30, 0, 'csgo', '5_headshot.png', 'Platinum Headshots'),
            ('Defused_The_Bomb', 50, 0, 'csgo', '6_defused_the_bomb.png', 'Supreme Bomb Defuser'),
            ('Planted_The_Bomb', 50, 0, 'csgo', '6_planted_the_bomb.png', 'Supreme Bomb Planter'),
            ('Rescued_A_Hostage', 50, 0, 'csgo', '6_rescued_a_hostage.png', 'Supreme Hostage Rescuer'),
            ('Killed_A_Hostage', 50, 0, 'csgo', '6_killed_a_hostage.png', 'Supreme Hostage Killer'),
            ('latency', 50, 0, 'csgo', '6_latency.png', 'Supreme Lowpinger'),
            ('headshot', 50, 0, 'csgo', '6_headshot.png', 'Supreme Headshots'),
            ('teamkills', 1, 0, 'csgo', '1_teamkills.png', 'Award of Team Kills'),
            ('teamkills', 5, 0, 'csgo', '2_teamkills.png', 'Bronze Team Kills'),
            ('teamkills', 12, 0, 'csgo', '3_teamkills.png', 'Silver Team Kills'),
            ('teamkills', 20, 0, 'csgo', '4_teamkills.png', 'Gold Team Kills'),
            ('teamkills', 30, 0, 'csgo', '5_teamkills.png', 'Platinum Team Kills'),
            ('teamkills', 50, 0, 'csgo', '6_teamkills.png', 'Supreme Team Kills'),
            ('mostkills', 1, 0, 'csgo', '1_mostkills.png', 'Award of Most Kills'),
            ('mostkills', 5, 0, 'csgo', '2_mostkills.png', 'Bronze Most Kills'),
            ('mostkills', 12, 0, 'csgo', '3_mostkills.png', 'Silver Most Kills'),
            ('mostkills', 20, 0, 'csgo', '4_mostkills.png', 'Gold Most Kills'),
            ('mostkills', 30, 0, 'csgo', '5_mostkills.png', 'Platinum Most Kills'),
            ('mostkills', 50, 0, 'csgo', '6_mostkills.png', 'Supreme Most Kills'),
            ('round_mvp', 1, 0, 'csgo', '1_round_mvp.png', 'Most Valuable Player'),
            ('round_mvp', 5, 0, 'csgo', '2_round_mvp.png', 'Bronze Most Valuable Player'),
            ('round_mvp', 12, 0, 'csgo', '3_round_mvp.png', 'Silver Most Valuable Player'),
            ('round_mvp', 20, 0, 'csgo', '4_round_mvp.png', 'Gold Most Valuable Player'),
            ('round_mvp', 30, 0, 'csgo', '5_round_mvp.png', 'Platinum Most Valuable Player'),
            ('round_mvp', 50, 0, 'csgo', '6_round_mvp.png', 'Supreme Most Valuable Player'),
            ('suicide', 1, 0, 'csgo', '1_suicide.png', 'Award of Most Suicides'),
            ('suicide', 5, 0, 'csgo', '2_suicide.png', 'Bronze Suicides'),
            ('suicide', 12, 0, 'csgo', '3_suicide.png', 'Silver Suicides'),
            ('suicide', 20, 0, 'csgo', '4_suicide.png', 'Gold Suicides'),
            ('suicide', 30, 0, 'csgo', '5_suicide.png', 'Platinum Suicides'),
            ('suicide', 50, 0, 'csgo', '6_suicide.png', 'Supreme Suicides');
    ");    
  
    $db->query("
        INSERT IGNORE INTO `hlstats_Teams` (`game`, `code`, `name`, `hidden`, `playerlist_bgcolor`, `playerlist_color`, `playerlist_index`) VALUES
            ('csgo', 'TERRORIST', 'Terrorist', '0', '#FFD5D5', '#FF2D2D', 1),
            ('csgo', 'CT', 'Counter-Terrorist', '0', '#D2E8F7', '#0080C0', 2);
    ");    
    
    $db->query("
        INSERT IGNORE INTO `hlstats_Weapons` (`game`, `code`, `name`, `modifier`) VALUES
            ('csgo', 'ak47', 'Kalashnikov AK-47', 1.00),
            ('csgo', 'm4a1', 'M4A4', 1.00),
            ('csgo', 'awp', 'AWP', 1.00),
            ('csgo', 'deagle', 'Desert Eagle', 1.20),
            ('csgo', 'hkp2000', 'P2000', 1.40),
            ('csgo', 'galilar', 'Galil', 1.10),
            ('csgo', 'glock', 'Glock-18', 1.40),
            ('csgo', 'bizon', 'PP-Bizon', 1.30),
            ('csgo', 'galil', 'Galil', 1.10),
            ('csgo', 'p90', 'FN P90', 1.20),
            ('csgo', 'aug', 'Steyr Aug', 1.00),
            ('csgo', 'mp7', 'MP7', 1.30),
            ('csgo', 'elite', 'Dual Berretta Elites', 1.40),
            ('csgo', 'ssg08', 'SSG 08', 1.10),
            ('csgo', 'sg553', 'SG 553', 1.00),
            ('csgo', 'nova', 'Nova', 1.30),
            ('csgo', 'p250', 'P250', 1.50),
            ('csgo', 'knife', 'Knife', 2.00),
            ('csgo', 'ump45', 'H&K UMP45', 1.20),
            ('csgo', 'sawedoff', 'Sawed-Off', 1.30),
            ('csgo', 'mag7', 'MAG-7', 1.30),
            ('csgo', 'hegrenade', 'High Explosive Grenade', 1.80),
            ('csgo', 'mp9', 'MP9', 1.40),
            ('csgo', 'tec9', 'Tec-9', 1.20),
            ('csgo', 'scar20', 'Scar-20', 0.80),
            ('csgo', 'xm1014', 'XM1014', 1.10),
            ('csgo', 'fiveseven', 'FN Five-Seven', 1.50),
            ('csgo', 'negev', 'Negev', 1.00),
            ('csgo', 'mac10', 'MAC-10', 1.50),
            ('csgo', 'g3sg1', 'H&K G3/SG1 Sniper Rifle', 0.80),
            ('csgo', 'm249', 'M249 PARA Light Machine Gun', 1.00),
            ('csgo', 'inferno', 'Incendiary Grenade', 1.80),
            ('csgo', 'taser', 'Zeus x27', 1.00);
    ");
    
    // Tracker #1589 - Add Dino D-Day support
    print "Adding Dino D-Day game support. (<a href=\"http://tracker.hlxce.com/issues/1589\">#1589</a>)<br />";
    
    $db->query("
        INSERT IGNORE INTO `hlstats_Actions` (`game`, `code`, `reward_player`, `reward_team`, `team`, `description`, `for_PlayerActions`, `for_PlayerPlayerActions`, `for_TeamActions`, `for_WorldActions`) VALUES
            ('dinodday', 'headshot', 3, 0, '', 'Boom! Headshot!', '1', '0', '0', '0'),
            ('dinodday', 'kill_goat', -10, 0, '', 'Defenseless Goat murdered', '1', '0', '0', '0'),
            ('dinodday', 'kill_streak_2', 1, 0, '', 'Double Kill (2 kills)', '1', '0', '0', '0'),
            ('dinodday', 'kill_streak_3', 2, 0, '', 'Triple Kill (3 kills)', '1', '0', '0', '0'),
            ('dinodday', 'kill_streak_4', 3, 0, '', 'Domination (4 kills)', '1', '0', '0', '0'),
            ('dinodday', 'kill_streak_5', 4, 0, '', 'Rampage (5 kills)', '1', '0', '0', '0'),
            ('dinodday', 'kill_streak_6', 5, 0, '', 'Mega Kill (6 kills)', '1', '0', '0', '0'),
            ('dinodday', 'kill_streak_7', 6, 0, '', 'Ownage (7 kills)', '1', '0', '0', '0'),
            ('dinodday', 'kill_streak_8', 7, 0, '', 'Ultra Kill (8 kills)', '1', '0', '0', '0'),
            ('dinodday', 'kill_streak_9', 8, 0, '', 'Killing Spree (9 kills)', '1', '0', '0', '0'),
            ('dinodday', 'kill_streak_10', 9, 0, '', 'Monster Kill (10 kills)', '1', '0', '0', '0'),
            ('dinodday', 'kill_streak_11', 10, 0, '', 'Unstoppable (11 kills)', '1', '0', '0', '0'),
            ('dinodday', 'kill_streak_12', 11, 0, '', 'God Like (12+ kills)', '1', '0', '0', '0');
    ");
    
    $db->query("
        INSERT IGNORE INTO `hlstats_Games` (`code`, `name`, `realgame`, `hidden`) VALUES 
            ('dinodday', 'Dino D-Day', 'dinodday', '1');
    ");

    $db->query("
        INSERT IGNORE INTO `hlstats_Games_Defaults` (`code`, `parameter`, `value`) VALUES    
            ('dinodday', 'Admins', ''),
            ('dinodday', 'AutoBanRetry', '0'),
            ('dinodday', 'AutoTeamBalance', '0'),
            ('dinodday', 'BonusRoundIgnore', '1'),
            ('dinodday', 'BonusRoundTime', '0'),
            ('dinodday', 'BroadCastEvents', '1'),
            ('dinodday', 'BroadCastPlayerActions', '1'),
            ('dinodday', 'ConnectAnnounce', '1'),
            ('dinodday', 'DefaultDisplayEvents', '1'),
            ('dinodday', 'DisplayResultsInBrowser', '1'),
            ('dinodday', 'EnablePublicCommands', '1'),
            ('dinodday', 'GameEngine', '3'),
            ('dinodday', 'GameType', '0'),
            ('dinodday', 'HLStatsURL', 'http://yoursite.com/hlstats'),
            ('dinodday', 'IgnoreBots', '1'),
            ('dinodday', 'MinimumPlayersRank', '0'),
            ('dinodday', 'MinPlayers', '4'),
            ('dinodday', 'PlayerEvents', '1'),
            ('dinodday', 'ShowStats', '1'),
            ('dinodday', 'SkillMode', '0'),
            ('dinodday', 'SuicidePenalty', '5'),
            ('dinodday', 'SwitchAdmins', '0'),
            ('dinodday', 'TKPenalty', '0'),
            ('dinodday', 'TrackServerLoad', '1'),
            ('dinodday', 'UpdateHostname', '1');
    ");

    $db->query("
        INSERT IGNORE INTO `hlstats_Games_Supported` (`code`, `name`) VALUES
            ('dinodday', 'Dino D-Day');
    ");

    $db->query("
        INSERT IGNORE INTO `hlstats_Ranks` (`game`, `image`, `minKills`, `maxKills`, `rankName`) VALUES
            ('dinodday', 'recruit', '0', '49', 'Recruit'),
            ('dinodday', 'private', '50', '99', 'Private'),
            ('dinodday', 'private-first-class', '100', '199', 'Private First Class'),
            ('dinodday', 'lance-corporal', '200', '299', 'Lance Corporal'),
            ('dinodday', 'corporal', '300', '399', 'Corporal'),
            ('dinodday', 'sergeant', '400', '499', 'Sergeant'),
            ('dinodday', 'staff-sergeant', '500', '599', 'Staff Sergeant'),
            ('dinodday', 'gunnery-sergeant', '600', '699', 'Gunnery Sergeant'),
            ('dinodday', 'master-sergeant', '700', '799', 'Master Sergeant'),
            ('dinodday', 'first-sergeant', '800', '899', 'First Sergeant'),
            ('dinodday', 'master-chief', '900', '999', 'Master Chief'),
            ('dinodday', 'sergeant-major', '1000', '1199', 'Sergeant Major'),
            ('dinodday', 'ensign', '1200', '1399', 'Ensign'),
            ('dinodday', 'third-lieutenant', '1400', '1599', 'Third Lieutenant'),
            ('dinodday', 'second-lieutenant', '1600', '1799', 'Second Lieutenant'),
            ('dinodday', 'first-lieutenant', '1800', '1999', 'First Lieutenant'),
            ('dinodday', 'captain', '2000', '2249', 'Captain'),
            ('dinodday', 'group-captain', '2250', '2499', 'Group Captain'),
            ('dinodday', 'senior-captain', '2500', '2749', 'Senior Captain'),
            ('dinodday', 'lieutenant-major', '2750', '2999', 'Lieutenant Major'),
            ('dinodday', 'major', '3000', '3499', 'Major'),
            ('dinodday', 'group-major', '3500', '3999', 'Group Major'),
            ('dinodday', 'lieutenant-commander', '4000', '4499', 'Lieutenant Commander'),
            ('dinodday', 'commander', '4500', '4999', 'Commander'),
            ('dinodday', 'group-commander', '5000', '5749', 'Group Commander'),
            ('dinodday', 'lieutenant-colonel', '5750', '6499', 'Lieutenant Colonel'),
            ('dinodday', 'colonel', '6500', '7249', 'Colonel'),
            ('dinodday', 'brigadier', '7250', '7999', 'Brigadier'),
            ('dinodday', 'brigadier-general', '8000', '8999', 'Brigadier General'),
            ('dinodday', 'major-general', '9000', '9999', 'Major General'),
            ('dinodday', 'lieutenant-general', '10000', '12499', 'Lieutenant General'),
            ('dinodday', 'general', '12500', '14999', 'General'),
            ('dinodday', 'commander-general', '15000', '17499', 'Commander General'),
            ('dinodday', 'field-vice-marshal', '17500', '19999', 'Field Vice Marshal'),
            ('dinodday', 'field-marshal', '20000', '22499', 'Field Marshal'),
            ('dinodday', 'vice-commander-of-the-army', '22500', '24999', 'Vice Commander of the Army'),
            ('dinodday', 'commander-of-the-army', '25000', '27499', 'Commander of the Army'),
            ('dinodday', 'high-commander', '27500', '29999', 'High Commander'),
            ('dinodday', 'supreme-commander', '30000', '34999', 'Supreme Commander'),
            ('dinodday', 'terminator', '35000', '9999999', 'Terminator');
    ");

    $db->query("
        INSERT IGNORE INTO `hlstats_Roles` (`game`, `code`, `name`, `hidden`) VALUES
            ('dinodday', '#class_blue_class2', 'Cpl. Joe Spencer', '0'),
            ('dinodday', '#class_blue_class1', 'Cpt. Jack Hardgrave', '0'),
            ('dinodday', '#class_red_class11', 'Microraptor', '0'),
            ('dinodday', '#class_red_class10', 'Compsognathus', '0'),
            ('dinodday', '#class_red_class7', 'Stygimoloch', '0'),
            ('dinodday', '#class_red_class6', 'Dilophosaurus', '0'),
            ('dinodday', '#class_red_class5', 'Desmatosuchus', '0'),
            ('dinodday', '#class_red_class4', 'Velociraptor', '0'),
            ('dinodday', '#class_red_class3', 'Hpt.Fw. Wolfgang von Graff', '0'),
            ('dinodday', '#class_red_class2', 'OLt. Karl Hissmann', '0'),
            ('dinodday', '#class_red_class1', 'Hptm. Kurt Streicher', '0'),
            ('dinodday', '#class_blue_class3', 'Cpt. Nigel Blithe-Crossley', '0'),
            ('dinodday', '#class_blue_class4', 'Ilona Vike', '0'),
            ('dinodday', '#class_blue_class5', 'Camille Brun', '0'),
            ('dinodday', '#class_blue_class6', 'Jakob Frank', '0'),
            ('dinodday', '#class_blue_class7', 'Trigger', '0');   
    ");   
    
    $db->query("
        INSERT IGNORE INTO `hlstats_Teams` (`game`, `code`, `name`, `hidden`, `playerlist_bgcolor`, `playerlist_color`, `playerlist_index`) VALUES
            ('dinodday', '#DDD_Team_Blue', 'Allies', '0', '#C1FFC1', '#006600', 2),
            ('dinodday', '#DDD_Team_Red', 'Axis', '0', '#FFD5D5', '#FF2D2D', 1);
    ");

    $db->query("
        INSERT IGNORE INTO `hlstats_Weapons` (`game`, `code`, `name`, `modifier`) VALUES
            ('dinodday', 'fists', 'Berserk Punch', 1.30),
            ('dinodday', 'flechette', 'Flechette Gun', 1.40),
            ('dinodday', 'jackrabbit', 'Jackrabbit', 1.40),
            ('dinodday', 'flak30', 'Desmatosuchus Flak 30', 1.30),
            ('dinodday', 'k98sniper', 'Karabiner 98 Sniper', 1.50),
            ('dinodday', 'mg42', 'Maschinengewehr 42', 1.20),
            ('dinodday', 'pterosaur', 'Pterosaur Strike', 1.30),
            ('dinodday', 'claws', 'Claw Attack', 1.70),
            ('dinodday', 'k98', 'Karabiner 98', 1.70),
            ('dinodday', 'mosin', 'Mosin Nagant', 1.50),
            ('dinodday', 'artillery', 'Artillery Strike', 1.20),
            ('dinodday', 'piat', 'PIAT Mk I', 1.20),
            ('dinodday', 'stickgrenade', 'Stielhandgranate 43', 1.40),
            ('dinodday', 'luger', 'P08 Luger', 1.60),
            ('dinodday', 'bar', 'Browning Automatic Rifle M1918', 1.20),
            ('dinodday', 'garand', 'M1 Garand', 1.30),
            ('dinodday', 'trenchknife', 'Kampfmesser', 1.70),
            ('dinodday', 'kabar', 'KA-BAR Combat Knife', 1.70),
            ('dinodday', 'pistol', 'Colt M1911', 1.60),
            ('dinodday', 'grenade', 'Hand Grenade MKII', 1.40),
            ('dinodday', 'shotgun', 'Trench Gun M1897', 1.40),
            ('dinodday', 'thompson', 'M1 Thompson', 1.20),
            ('dinodday', 'mp40', 'Maschinenpistole 40', 1.20),
            ('dinodday', 'sticky', 'Sticky Bomb', 1.40),
            ('dinodday', 'mp44', 'Sturmgewehr 44', 1.20),
            ('dinodday', 'dilophosaurus', 'Dilophosaurus Claws', 1.70),
            ('dinodday', 'satchel', 'Satchel Charge', 1.30),
            ('dinodday', 'sten', 'Sten Mk II', 1.20),
            ('dinodday', 'p38', 'Pistole 38', 1.60),
            ('dinodday', 'nagant', 'Nagant M1894', 1.60),
            ('dinodday', 'fistsregular', 'Fists', 1.70),
            ('dinodday', 'styracosaur', 'Styracosaur', 1.30),
            ('dinodday', 'trex', 'T-Rex Dual-MG42', 1.20),
            ('dinodday', 'trexbomb', 'T-Rex Bomb Throw', 1.50),
            ('dinodday', 'tankmine', 'Tankmine', 1.30),
            ('dinodday', 'trigger', 'Trigger .30cal', 1.20),
            ('dinodday', 'stygimoloch', 'Stygimoloch MG34', 1.20),
            ('dinodday', 'compy', 'Compsognathus', 1.70),
            ('dinodday', 'flamethrower', 'Flamethrower', 1.40),
            ('dinodday', 'microraptor', 'Microraptor Claws', 1.70),
            ('dinodday', 'carbine', 'M1 Carbine', 1.25),
            ('dinodday', 'greasegun', 'M3 Grease Gun', 1.20),
            ('dinodday', 'pounce', 'Velociraptor Pounce', 1.70),
            ('dinodday', 'desmamelee', 'Desmatosuchus Melee', 1.70),
            ('dinodday', 'body', 'Dilophosaurus Body Throw', 1.30),
            ('dinodday', 'stygihead', 'Stygimoloch Headbutt', 1.70),
            ('dinodday', 'suicide', 'Compsognathus Suicidebomb', 1.70),
            ('dinodday', 'spit', 'Microraptor Acidspit', 1.70),
            ('dinodday', 'triggerhead', 'Trigger Headbutt', 1.70),
            ('dinodday', 'dinner', 'T-Rex Dinner', 1.70),
            ('dinodday', 'stomp', 'T-Rex Stomp', 1.70),
            ('dinodday', 'goat', 'Dilophosaurus Goat Throw', 1.90);
    ");
    
    
    // Perform database schema update notification
    print "Updating database and verion schema numbers.<br />";
    $db->query("UPDATE hlstats_Options SET `value` = '$version' WHERE `keyname` = 'version'");
    $db->query("UPDATE hlstats_Options SET `value` = '$dbversion' WHERE `keyname` = 'dbversion'");
?>