DELETE FROM `hlstats_Ribbons` WHERE game = 'tf';

INSERT INTO `hlstats_Ribbons` (`awardCode`, `awardCount`, `special`, `game`, `image`, `ribbonName`) VALUES
('tf_projectile_rocket',1,0,'tf','1_tf_projectile_rocket.png','Bronze Rocket Launcher'),
('tf_projectile_rocket',5,0,'tf','2_tf_projectile_rocket.png','Silver Rocket Launcher'),
('tf_projectile_rocket',10,0,'tf','3_tf_projectile_rocket.png','Gold Rocket Launcher'),
('sniperrifle',1,0,'tf','1_sniperrifle.png','Bronze Sniper Rifle'),
('sniperrifle',5,0,'tf','2_sniperrifle.png','Silver Sniper Rifle'),
('sniperrifle',10,0,'tf','3_sniperrifle.png','Gold Sniper Rifle'),
('minigun',1,0,'tf','1_minigun.png','Bronze Minigun'),
('minigun',5,0,'tf','2_minigun.png','Silver Minigun'),
('minigun',10,0,'tf','3_minigun.png','Gold Minigun'),
('obj_sentrygun',1,0,'tf','1_obj_sentrygun.png','Bronze Sentry Gun'),
('obj_sentrygun',5,0,'tf','2_obj_sentrygun.png','Silver Sentry Gun'),
('obj_sentrygun',10,0,'tf','3_obj_sentrygun.png','Gold Sentry Gun'),
('knife',1,0,'tf','1_knife.png','Bronze Knife'),
('knife',5,0,'tf','2_knife.png','Silver Knife'),
('knife',10,0,'tf','3_knife.png','Gold Knife'),
('scattergun',1,0,'tf','1_scattergun.png','Bronze Scatter Gun'),
('scattergun',5,0,'tf','2_scattergun.png','Silver Scatter Gun'),
('scattergun',10,0,'tf','3_scattergun.png','Gold Scatter Gun'),
('tf_projectile_pipe',1,0,'tf','1_tf_projectile_pipe.png','Bronze Grenade Launcher'),
('tf_projectile_pipe',5,0,'tf','2_tf_projectile_pipe.png','Silver Grenade Launcher'),
('tf_projectile_pipe',10,0,'tf','3_tf_projectile_pipe.png','Gold Grenade Launcher'),
('flamethrower',1,0,'tf','1_flamethrower.png','Bronze Flamethrower'),
('flamethrower',5,0,'tf','2_flamethrower.png','Silver Flamethrower'),
('flamethrower',10,0,'tf','3_flamethrower.png','Gold Flamethrower'),
('tf_projectile_pipe_remote',1,0,'tf','1_tf_projectile_pipe_remote.png','Bronze Sticky Launcher'),
('tf_projectile_pipe_remote',5,0,'tf','2_tf_projectile_pipe_remote.png','Silver Sticky Launcher'),
('tf_projectile_pipe_remote',10,0,'tf','3_tf_projectile_pipe_remote.png','Gold Sticky Launcher'),
('shotgun_primary',1,0,'tf','1_shotgun_primary.png','Bronze Engy Shotgun'),
('shotgun_primary',5,0,'tf','2_shotgun_primary.png','Silver Engy Shotgun'),
('shotgun_primary',10,0,'tf','3_shotgun_primary.png','Gold Engy Shotgun'),
('smg',1,0,'tf','1_smg.png','Bronze Submachine Gun'),
('smg',5,0,'tf','2_smg.png','Silver Submachine Gun'),
('smg',10,0,'tf','3_smg.png','Gold Submachine Gun'),
('shotgun_soldier',1,0,'tf','1_shotgun_soldier.png','Bronze Soldier Shotgun'),
('shotgun_soldier',5,0,'tf','2_shotgun_soldier.png','Silver Soldier Shotgun'),
('shotgun_soldier',10,0,'tf','3_shotgun_soldier.png','Gold Soldier Shotgun'),
('revolver',1,0,'tf','1_revolver.png','Bronze Revolver'),
('revolver',5,0,'tf','2_revolver.png','Silver Revolver'),
('revolver',10,0,'tf','3_revolver.png','Gold Revolver'),
('shotgun_pyro',1,0,'tf','1_shotgun_pyro.png','Bronze Pyro Shotgun'),
('shotgun_pyro',5,0,'tf','2_shotgun_pyro.png','Silver Pyro Shotgun'),
('shotgun_pyro',10,0,'tf','3_shotgun_pyro.png','Gold Pyro Shotgun'),
('bat',1,0,'tf','1_bat.png','Bronze Bat'),
('bat',5,0,'tf','2_bat.png','Silver Bat'),
('bat',10,0,'tf','3_bat.png','Gold Bat'),
('wrench',1,0,'tf','1_wrench.png','Bronze Wrench'),
('wrench',5,0,'tf','2_wrench.png','Silver Wrench'),
('wrench',10,0,'tf','3_wrench.png','Gold Wrench'),
('shotgun_hwg',1,0,'tf','1_shotgun_hwg.png','Bronze Heavy Shotgun'),
('shotgun_hwg',5,0,'tf','2_shotgun_hwg.png','Silver Heavy Shotgun'),
('shotgun_hwg',10,0,'tf','3_shotgun_hwg.png','Gold Heavy Shotgun'),
('club',1,0,'tf','1_club.png','Bronze Machete'),
('club',5,0,'tf','2_club.png','Silver Machete'),
('club',10,0,'tf','3_club.png','Gold Machete'),
('pistol_scout',1,0,'tf','1_pistol_scout.png','Bronze Scout Pistol'),
('pistol_scout',5,0,'tf','2_pistol_scout.png','Silver Scout Pistol'),
('pistol_scout',10,0,'tf','3_pistol_scout.png','Gold Scout Pistol'),
('pistol',1,0,'tf','1_pistol.png','Bronze Engy Pistol'),
('pistol',5,0,'tf','2_pistol.png','Silver Engy Pistol'),
('pistol',10,0,'tf','3_pistol.png','Gold Engy Pistol'),
('bottle',1,0,'tf','1_bottle.png','Bronze Bottle'),
('bottle',5,0,'tf','2_bottle.png','Silver Bottle'),
('bottle',10,0,'tf','3_bottle.png','Gold Bottle'),
('shovel',1,0,'tf','1_shovel.png','Bronze Shovel'),
('shovel',5,0,'tf','2_shovel.png','Silver Shovel'),
('shovel',10,0,'tf','3_shovel.png','Gold Shovel'),
('fireaxe',1,0,'tf','1_fireaxe.png','Bronze Fire Axe'),
('fireaxe',5,0,'tf','2_fireaxe.png','Silver Fire Axe'),
('fireaxe',10,0,'tf','3_fireaxe.png','Gold Fire Axe'),
('fists',1,0,'tf','1_fists.png','Bronze Fists'),
('fists',5,0,'tf','2_fists.png','Silver Fists'),
('fists',10,0,'tf','3_fists.png','Gold Fists'),
('ubersaw',1,0,'tf','1_ubersaw.png','Bronze Ubersaw'),
('ubersaw',5,0,'tf','2_ubersaw.png','Silver Ubersaw'),
('ubersaw',10,0,'tf','3_ubersaw.png','Gold Ubersaw'),
('blutsauger',1,0,'tf','1_blutsauger.png','Bronze Blutsauger'),
('blutsauger',5,0,'tf','2_blutsauger.png','Silver Blutsauger'),
('blutsauger',10,0,'tf','3_blutsauger.png','Gold Blutsauger'),
('axtinguisher',1,0,'tf','1_axtinguisher.png','Bronze Axtinguisher'),
('axtinguisher',5,0,'tf','2_axtinguisher.png','Silver Axtinguisher'),
('axtinguisher',10,0,'tf','3_axtinguisher.png','Gold Axtinguisher'),
('deflect_flare',1,0,'tf','1_deflect_flare.png','Bronze Deflected Flare'),
('deflect_flare',5,0,'tf','2_deflect_flare.png','Silver Deflected Flare'),
('deflect_flare',10,0,'tf','3_deflect_flare.png','Gold Deflected Flare'),
('syringegun_medic',1,0,'tf','1_syringegun_medic.png','Bronze Syringe Gun'),
('syringegun_medic',5,0,'tf','2_syringegun_medic.png','Silver Syringe Gun'),
('syringegun_medic',10,0,'tf','3_syringegun_medic.png','Gold Syringe Gun'),
('bonesaw',1,0,'tf','1_bonesaw.png','Bronze Bonesaw'),
('bonesaw',5,0,'tf','2_bonesaw.png','Silver Bonesaw'),
('bonesaw',10,0,'tf','3_bonesaw.png','Gold Bonesaw'),
('deflect_promode',1,0,'tf','1_deflect_promode.png','Bronze Deflected Grenade'),
('deflect_promode',5,0,'tf','2_deflect_promode.png','Silver Deflected Grenade'),
('deflect_promode',10,0,'tf','3_deflect_promode.png','Gold Deflected Grenade'),
('deflect_rocket',1,0,'tf','1_deflect_rocket.png','Bronze Deflected Rocket'),
('deflect_rocket',5,0,'tf','2_deflect_rocket.png','Silver Deflected Rocket'),
('deflect_rocket',10,0,'tf','3_deflect_rocket.png','Gold Deflected Rocket'),
('deflect_sticky',1,0,'tf','1_deflect_sticky.png','Bronze Deflected Sticky'),
('deflect_sticky',5,0,'tf','2_deflect_sticky.png','Silver Deflected Sticky'),
('deflect_sticky',10,0,'tf','3_deflect_sticky.png','Gold Deflected Sticky'),
('flaregun',1,0,'tf','1_flaregun.png','Bronze Flare Gun'),
('flaregun',5,0,'tf','2_flaregun.png','Silver Flare Gun'),
('flaregun',10,0,'tf','3_flaregun.png','Gold Flare Gun'),
('natascha',1,0,'tf','1_natascha.png','Bronze Natascha'),
('natascha',5,0,'tf','2_natascha.png','Silver Natascha'),
('natascha',10,0,'tf','3_natascha.png','Gold Natascha'),
('gloves',1,0,'tf','1_gloves.png','Bronze K.G.B.'),
('gloves',5,0,'tf','2_gloves.png','Silver K.G.B.'),
('gloves',10,0,'tf','3_gloves.png','Gold K.G.B.'),
('taunt_heavy',1,0,'tf','1_taunt_heavy.png','Bronze Heavy Taunt'),
('taunt_heavy',5,0,'tf','2_taunt_heavy.png','Silver Heavy Taunt'),
('taunt_heavy',10,0,'tf','3_taunt_heavy.png','Gold Heavy Taunt'),
('taunt_pyro',1,0,'tf','1_taunt_pyro.png','Bronze Hadouken'),
('taunt_pyro',5,0,'tf','2_taunt_pyro.png','Silver Hadouken'),
('taunt_pyro',10,0,'tf','3_taunt_pyro.png','Gold Hadouken'),
('chargedeployed',1,0,'tf','1_chargedeployed.png','Bronze Uber'),
('chargedeployed',5,0,'tf','2_chargedeployed.png','Silver Uber'),
('chargedeployed',10,0,'tf','3_chargedeployed.png','Gold Uber'),
('sandvich',1,0,'tf','1_sandvich.png','Bronze Sandvich'),
('sandvich',5,0,'tf','2_sandvich.png','Silver Sandvich'),
('sandvich',10,0,'tf','3_sandvich.png','Gold Sandvich'),
('domination',1,0,'tf','1_domination.png','Bronze Dominator'),
('domination',5,0,'tf','2_domination.png','Silver Dominator'),
('domination',10,0,'tf','3_domination.png','Gold Dominator'),
('revenge',1,0,'tf','1_revenge.png','Bronze Revenger'),
('revenge',5,0,'tf','2_revenge.png','Silver Revenger'),
('revenge',10,0,'tf','3_revenge.png','Gold Revenger'),
('mostkills',1,0,'tf','1_mostkills.png','Bronze Kill Award'),
('mostkills',5,0,'tf','2_mostkills.png','Silver Kill Award'),
('mostkills',10,0,'tf','3_mostkills.png','Gold Kill Award'),
('backstab',1,0,'tf','1_backstab.png','Bronze Backstabber'),
('backstab',5,0,'tf','2_backstab.png','Silver Backstabber'),
('backstab',10,0,'tf','3_backstab.png','Gold Backstabber'),
('pointcaptured',1,0,'tf','1_pointcaptured.png','Bronze Capture Point'),
('pointcaptured',5,0,'tf','2_pointcaptured.png','Silver Capture Point'),
('pointcaptured',10,0,'tf','3_pointcaptured.png','Gold Capture Point'),
('captureblocked',1,0,'tf','1_captureblocked.png','Bronze Blocker'),
('captureblocked',5,0,'tf','2_captureblocked.png','Silver Blocker'),
('captureblocked',10,0,'tf','3_captureblocked.png','Gold Blocker'),
('flagevent_defended',1,0,'tf','1_flagevent_defended.png','Bronze Defender'),
('flagevent_defended',5,0,'tf','2_flagevent_defended.png','Silver Defender'),
('flagevent_defended',10,0,'tf','3_flagevent_defended.png','Gold Defender'),
('flagevent_captured',1,0,'tf','1_flagevent_captured.png','Bronze Intelligence'),
('flagevent_captured',5,0,'tf','2_flagevent_captured.png','Silver Intelligence'),
('flagevent_captured',10,0,'tf','3_flagevent_captured.png','Gold Intelligence'),
('kill assist',1,0,'tf','1_kill assist.png','Bronze Assister'),
('kill assist',5,0,'tf','2_kill assist.png','Silver Assister'),
('kill assist',10,0,'tf','3_kill assist.png','Gold Assister'),
('bonuspoints',1,0,'tf','1_bonuspoints.png','Bronze Healer'),
('bonuspoints',5,0,'tf','2_bonuspoints.png','Silver Healer'),
('bonuspoints',10,0,'tf','3_bonuspoints.png','Gold Healer'),
('kill_assist_medic',1,0,'tf','1_kill_assist_medic.png','Bronze Healer'),
('kill_assist_medic',5,0,'tf','2_kill_assist_medic.png','Silver Healer'),
('kill_assist_medic',10,0,'tf','3_kill_assist_medic.png','Gold Healer'),
('builtobject_obj_attachment_sapper',1,0,'tf','1_builtobject_obj_attachement_sapper.png','Bronze Sapper'),
('builtobject_obj_attachment_sapper',5,0,'tf','2_builtobject_obj_attachement_sapper.png','Silver Sapper'),
('builtobject_obj_attachment_sapper',10,0,'tf','3_builtobject_obj_attachement_sapper.png','Gold Sapper');

INSERT IGNORE INTO `hlstats_Awards` (`awardType`, `game`, `code`, `name`, `verb`) VALUES
('W','tf','tf_projectile_pipe_remote','Remote Demolition Man','pipe bomb kills'),
('W','tf','tf_projectile_pipe','Demolition Man','pipe bomb kills'),
('W','tf','sniperrifle','Top Sniper','snipings'),
('W','tf','smg','Submachine gun','smg kills'),
('W','tf','shotgun_soldier','Shotgun Soldier','shotgun kills'),
('W','tf','shotgun_pyro','Shotgun Pyro','shotgun kills'),
('W','tf','shotgun_primary','Shotgun','shotgun kills'),
('W','tf','scattergun','Fast and Furious','scattergun kills'),
('W','tf','revolver','Wayne','revolver kills'),
('W','tf','pistol','Pistol','pistol kills'),
('W','tf','obj_sentrygun','Engineer','sentry kills'),
('W','tf','minigun','Terminator','minigun kills'),
('W','tf','knife','Stabber','knifings'),
('W','tf','flamethrower','Pyro','flame burnings'),
('W','tf','bat','Baseball freak','bat kills'),
('O','tf','pointcaptured','Capturer','checkpoint captures'),
('O','tf','kill assist','Assistance','kill assists'),
('O','tf','captureblocked','Blocker','checkpoint blockings'),
('O','tf','chargedeployed','Ubermedic','deployed charges'),
('W','tf','latency','Best Latency','ms average connection'),
('W','tf','tf_projectile_rocket','Soldier','rocket kills'),
('W','tf','wrench','Engineer on Rage','wrench kills'),
('W','tf','shovel','Grave Digger','shovel kills'),
('W','tf','fireaxe','Axe-O-Mania','axe kills'),
('W','tf','bottle','Drunken Demoman','bottle kills'),
('W','tf','bonesaw','The Saw','sawed bones'),
('W','tf','fists','Fisting king','fistings'),
('W','tf','club','Now that\'s a knife','machete kills'),
('W','tf','pistol_scout','Scout Pistol','pistol kills'),
('W','tf','shotgun_hwg','Shotgun Heavy','shotgun kills'),
('W','tf','syringegun_medic','The Injector','syringe kills'),
('W','tf','axtinguisher', 'Axtinguisher', 'kills with the axtinguisher'),
('W','tf','backburner', 'Backburner', 'burned backs'),
('W','tf','blutsauger', 'Blutsauger', 'times sucked blood'),
('W','tf','flaregun', 'Flare Gun', 'flare gun kills'),
('W','tf','gloves', 'Heavy surgery', 'KGB kills'),
('W','tf','natascha', 'Nataschas Friend', 'Natascha kills'),
('W','tf','ubersaw', 'Ubersaw', 'kills with ubersaw'),
('W','tf','deflect_flare', 'Deflected Flare', 'kills with deflected flare'),
('W','tf','deflect_promode', 'Deflected Grenade', 'kills with deflected grenade'),
('W','tf','deflect_rocket', 'Deflected Rocket', 'kills with deflected rocket'),
('W','tf','deflect_sticky', 'Deflected Sticky', 'kills with deflected sticky'),
('W','tf','taunt_heavy', 'POW! Ha Ha', 'kills with heavy taunt'),
('W','tf','taunt_pyro', 'Hadouken', 'kills with Hadouken'),
('W','tf','mostkills','Most Kills','kills'),
('W','tf','bonuspoints','Most Bonus Points','bonus points'),
('O','tf', 'sandvich', 'Hungry Hungry Heavy', 'sandviches eaten'),
('O','tf', 'backstab', 'Backstabber', 'backstabs'),
('O','tf','flagevent_defended','Defender of the Flag','flag defenses'),
('O','tf','flagevent_captured','The Mad Capper','flag captures'),
('O','tf','killedobject_obj_dispenser','NO METAL FOR YOU!','dispensers destroyed'),
('O','tf','killedobject_obj_sentrygun','Say no to sentries','sentry guns destroyed'),
('O','tf','builtobject_obj_sentrygun','Bob the Builder','sentry guns built'),
('O','tf','builtobject_obj_attachment_sapper','Super Sapper','sappers placed'),
('O','tf','kill_assist_medic','Medic Assistance','medic assists');